version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - node --version
      - npm install
  
  build:
    commands:
      - npm run build --prod
  
  post_build:
    commands:
      - echo "Build abgeschlossen"

artifacts:
  files:
    - '**/*'
  base-directory: www
  discard-paths: no
  secondary-artifacts:
    InfrastructureTemplate:
      files:
        - infrastructure.yaml
      discard-paths: yes
