version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - node --version
      - npm install
  
  build:
    commands:
      - npm run build --prod
  
  post_build:
    commands:
      - echo "Build abgeschlossen"
      - cp infrastructure.yaml www/
      - mkdir -p deploy_root
      - cp -r www/* deploy_root/

artifacts:
  files:
    - '**/*'
  base-directory: deploy_root
  discard-paths: yes
