version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install
  
  build:
    commands:
      - npm run build -- --prod
  
  post_build:
    commands:
      - echo "Build abgeschlossen"

artifacts:
  files:
    - www/**/*
    - infrastructure.yaml
  discard-paths: no
