version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - node --version
      - npm install
  
  build:
    commands:
      - npm run build --prod
  
  post_build:
    commands:
      - echo "Build abgeschlossen"

artifacts:
  files:
    - '**/*'
    - ../infrastructure.yaml
  base-directory: www/www
  discard-paths: no
