version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g n
      - n 20.19.0
      - node --version
      - npm install
  
  build:
    commands:
      - npm run build -- --prod
  
  post_build:
    commands:
      - echo "Build abgeschlossen"

artifacts:
  files:
    - www/**/*
    - infrastructure.yaml
  discard-paths: no
